title: Muhammad Farhan Ahmed
logo: /assets/img/my-pic-infromal.jpg
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman


#theme: jekyll-theme-slate
theme: jekyll-theme-midnight
#theme: jekyll-theme-architect
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-modernist
#theme: jekyll-theme-primer

# Social media usernames
twitter_username: username
#github_username: username
#linkedin_username: your-linkedin-username
#google_scholar_url: "https://scholar.google.com/citations?user=your-google-scholar-id"

# Additional configuration options
social:
  twitter: "https://twitter.com/username"
  #github: "https://github.com/username"
  #linkedin: "https://www.linkedin.com/in/your-linkedin-username"
  #google_scholar: "https://scholar.google.com/citations?user=your-google-scholar-id"
